// Keep this list exactly as supplied. Duplicate entries intentionally remain and
// give that value additional selection weight whenever the name is available.
const SYSTEM_ROOM_NAMES = [
   "Addis_King",
  "Habesha#Pro",
  "Karta&Friends",
  "100Birr•Room",
  "ShegerBoyz",
  "Arada@Night",
  "Ethio__Gamerz%",
  "Lucky🍀Habesha",
  "★Nooboch_Only",
  "Addis$Winner",
  "Win_Birrr",
  "Karta🎮Kinggg",
  "Pro*Playerz!",
  "Genzeb@Ale💸",
  "Enchawet_Bro",
  "Yene❤️Karta",
  "꧁Jegna_Players",
  "Negus#Table",
  "Ashenafi@Room★",
  "Gobezoch&Gibu",
  "Man_Yashenefal",
  "Atfer🔥_Giba",
  "Dil💸EnaBirr",
  "Arada_Kingz",
  "亗Habesha_Jackpot%",
  "AddisProoo",
  "Karta4Life🎮",
  "Birr&Birr_Birrr",
  "Easy$Moneyy",
  "Win_Or_Cry",
  "LastGame_Walahi",
  "NoCheat_Pls",
  "★NoLag@Bro!",
  "Wifi_Yelem",
  "Battery2%",
  "Tomorrow📚_Exam",
  "WorkLay#Negn",
  "Manager@Ayegnim",
  "Brooo_JoinFast",
  "RoomFull_Soon",
  "DontJoin_Pls",
  "Come🏆&Win",
  "Lets_Gooo!!",
  "OnlyLegendzz",
  "Karta_Masterr",
  "FakePro😂",
  "Real_Noob",
  "Noob#Master",
  "BigBoss_Room",
  "♛KingOf_Karta★",
  "AddisBoy_09",
  "HabeshaGirlz💅",
  "Boys⚔️_Vs_Girls",
  "Bole@Players",
  "Sheger_Legends",
  "WolloKingz",
  "Gondar_Boyz",
  "JimmaPro_Room",
  "Mekelle🎮&Gamerz",
  "Hawassa_Night🌙",
  "Adama_Winners",
  "BahirDar#King",
  "DireDawa_Crew",
  "HararLegends",
  "Dessie_Players",
  "ArbaMinch@Pro",
  "★ShashamaneBoyz%",
  "Ethiopia_No1",
  "Ethio251_Gamerz🇪🇹",
  "AddisAbaba_01",
  "HabeshaForever❤️",
  "Karta_Family",
  "FriendsOnlyyy",
  "FriendsOnlyyy",
  "Chill☕&EnaPlay",
  "Bunna☕EnaKarta",
  "Chat_Behualla",
  "Zena_Belen",
  "Selam@New",
  "EndetNeh_Bro😂",
  "DehnaNesh_Queen👑",
  "Gibu_Enchawet",
  "Enchawettt!",
  "Atwta_Koy",
  "Ahun#Newww⚡",
  "Befit_Giba",
  "ManAle_Endene",
  "Ene_Alshenfem",
  "Shinfet_Yelem",
  "Yezare_Ashenafi🏆",
  "Edlenya🍀Room",
  "Werek_Table✨",
  "Dil🔥Room",
  "Esat_Players🔥",
  "Mebrek⚡@Gamerz",
  "Anbessa_Crew🦁",
  "NebrBoyz🐅",
  "Tekula_Room🐺",
  "Nisr_Players🦅",
  "JegnaSquad💪",
  "Aleka@Room😎",
  "Abat_New😂",
  "Gobez_Bicha🏆",
  "Fetan_Game⚡",
  "Kebad#Room😈",
  "Gud_Neww😂",
  "Genzeb$Room💰",
  "Jackpottt🎰!",
  "Lucky🍀Cashh",
  "Golden✨Table",
  "Ace🂡Master",
  "NoExittt😈!",
  "SecretRoom_007🕵️",
  "Fire🔥Playerz",
  "Lag📶#King",
  "Karta@Nooboch🤡",
  "አራዳ", "ሀበሻ", "ወርቅ✨", "ድል", "ጉድ",
  "ከባድ", "ፈጣን⚡", "አደገኛ", "ቻምፒዮን", "ተጫዋች",
  "አለቃ", "አባት", "ነብር", "አንበሳ", "ብር",
  "ገንዘብ", "ሽልማት", "ዕድል", "ካርታ", "ቁማር",
  "እሳት", "መብረቅ⚡", "ኃይል", "ኩሩ", "ጎበዝ",
  "ምርጥ", "ዋና", "ተኩላ", "ንስር", "ጭልፊት",
  "አሸናፍ", "ንጉሥሽ", "ንጉስስ", "ጀግናው", "ጀግናአ",
  "አራዳው", "አራዳአ", "ሀበሻው", "ሀበሻአ", "እድለኛ",
  "እድለኛው", "ወርቅክ", "ወርቅቅ", "ድልል", "ጉድድ",
  "ከባድድ", "ፈጣንን", "አደገኛው", "ቻምፕዮን", "ቻምፒዮንን",
  "ተጫዋችች", "አለቃው", "አለቃአ", "አባትት", "ነብርር",
  "አንበሳው", "አንበሳአ", "ብርር", "ገንዘብብ", "ሽልማትት",
  "እድልል", "ካርታአ", "ካርታታ", "ቁማርር", "እሳትት",
  "መብረቅቅ", "ሀይልል", "ኩሩው", "ጎበዝዝ", "ምርጥጥ",
  "ዋናአ", "ተኩላው", "ንስርር", "ጭልፊትት", "ሸገር",
  "ሸገርር", "ቦሌ", "ቦሌኤ", "አዲስ", "አዲስስ",
  "ጎንደር", "ጎንደርር", "ወሎ", "ወሎው", "ጅማ",
  "ጅማአ", "ሀዋሳ", "ሀዋሳአ", "መቀሌ", "መቀሌኤ",
  "አዳማ", "አዳማአ", "ባህርዳር", "ባህርዳርር", "ዘና",
"ፈጣን⚡",
  "አደገኛ😈",
  "አንበሳ🦁",
  "ብር💸",
  "ገንዘብ💰",
  "ሽልማት🎁",
  "ካርታ🃏",
  "እሳት🔥",
  "ቦስስ", "ኪንግ", "ኪንግግ", "ሌጀንድ", "ሌጀንድድ",
  "ጃክፖት", "ጃክፖትት", "ቦነስ", "ቦነስስ", "ካሽ", "ካሽሽ",
];

module.exports = { SYSTEM_ROOM_NAMES };
